# Generated by Django 3.1 on 2020-09-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeds',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='feeds',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='feeds',
            name='subtitle',
            field=models.CharField(blank=True, max_length=144),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='title',
            field=models.CharField(max_length=144),
        ),
    ]
